-- ============================================================================
-- Project : Online Bookstore Sales Analysis
-- Database: PostgreSQL
--
-- Description:
-- This file contains advanced SQL queries used to solve real-world business
-- problems using Joins, Aggregate Functions, CTEs, Window Functions,
-- Ranking Functions, and Date Functions.
--
-- Author : Shobhit Kushwaha
-- ============================================================================


-- ============================================================================
-- Question 10
-- Find customers who have never placed an order.
-- ============================================================================

SELECT
    c.customer_id,
    c.name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL
ORDER BY c.customer_id;


-- ============================================================================
-- Question 11
-- Find the top five customers based on total amount spent.
-- ============================================================================

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY total_spent DESC
LIMIT 5;


-- ============================================================================
-- Question 12
-- Find customers who purchased books from more than one genre.
-- ============================================================================

SELECT
    c.customer_id,
    c.name,
    COUNT(DISTINCT b.genre) AS genres_purchased
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN books b
    ON o.book_id = b.book_id
GROUP BY
    c.customer_id,
    c.name
HAVING COUNT(DISTINCT b.genre) > 1
ORDER BY genres_purchased DESC;


-- ============================================================================
-- Question 13
-- Find all books that have never been ordered.
-- ============================================================================

SELECT
    b.book_id,
    b.title
FROM books b
LEFT JOIN orders o
    ON b.book_id = o.book_id
WHERE o.book_id IS NULL
ORDER BY b.book_id;


-- ============================================================================
-- Question 14
-- Find the top-selling author based on total quantity sold.
-- ============================================================================

SELECT
    b.author,
    SUM(o.quantity) AS total_books_sold
FROM books b
JOIN orders o
    ON b.book_id = o.book_id
GROUP BY b.author
ORDER BY total_books_sold DESC
LIMIT 1;


-- ============================================================================
-- Question 15
-- Calculate the total revenue generated by each genre.
-- ============================================================================

SELECT
    b.genre,
    SUM(o.total_amount) AS total_revenue
FROM books b
JOIN orders o
    ON b.book_id = o.book_id
GROUP BY b.genre
ORDER BY total_revenue DESC;


-- ============================================================================
-- Question 16
-- Calculate the average order value for each customer.
-- ============================================================================

SELECT
    c.customer_id,
    c.name,
    ROUND(AVG(o.total_amount), 2) AS average_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY c.customer_id;


-- ============================================================================
-- Question 17
-- Find the city that generated the highest revenue.
-- ============================================================================

SELECT
    c.city,
    SUM(o.total_amount) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY total_revenue DESC
LIMIT 1;


-- ============================================================================
-- Question 18
-- Find the month with the highest sales revenue.
-- ============================================================================

SELECT
    DATE_TRUNC('month', order_date) AS sales_month,
    SUM(total_amount) AS monthly_revenue
FROM orders
GROUP BY DATE_TRUNC('month', order_date)
ORDER BY monthly_revenue DESC
LIMIT 1;


-- ============================================================================
-- Question 19
-- Calculate each genre's percentage contribution to total revenue.
-- ============================================================================

SELECT
    b.genre,
    SUM(o.total_amount) AS genre_revenue,
    ROUND(
        (SUM(o.total_amount) /
        (SELECT SUM(total_amount) FROM orders)) * 100,
        2
    ) AS revenue_percentage
FROM books b
JOIN orders o
    ON b.book_id = o.book_id
GROUP BY b.genre
ORDER BY revenue_percentage DESC;


-- ============================================================================
-- Question 20
-- Compare each month's revenue with the previous month.
-- ============================================================================

WITH monthly_sales AS (

    SELECT
        DATE_TRUNC('month', order_date) AS sales_month,
        SUM(total_amount) AS current_month_revenue
    FROM orders
    GROUP BY DATE_TRUNC('month', order_date)

)

SELECT
    sales_month,
    current_month_revenue,
    LAG(current_month_revenue, 1, 0)
        OVER (ORDER BY sales_month) AS previous_month_revenue,
    current_month_revenue -
    LAG(current_month_revenue, 1, 0)
        OVER (ORDER BY sales_month) AS revenue_difference
FROM monthly_sales
ORDER BY sales_month;


-- ============================================================================
-- Question 21
-- Rank customers based on their total spending.
-- ============================================================================

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spending,
    RANK() OVER (
        ORDER BY SUM(o.total_amount) DESC
    ) AS spending_rank
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY spending_rank;


-- ============================================================================
-- Question 22
-- Find the highest-selling book in each genre.
-- ============================================================================

WITH book_sales AS (

    SELECT
        b.book_id,
        b.title,
        b.genre,
        SUM(o.quantity) AS total_books_sold
    FROM books b
    JOIN orders o
        ON b.book_id = o.book_id
    GROUP BY
        b.book_id,
        b.title,
        b.genre

),

ranked_books AS (

    SELECT
        *,
        DENSE_RANK() OVER (
            PARTITION BY genre
            ORDER BY total_books_sold DESC
        ) AS sales_rank
    FROM book_sales

)

SELECT
    book_id,
    title,
    genre,
    total_books_sold
FROM ranked_books
WHERE sales_rank = 1
ORDER BY genre;